# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the giantswarm/muster release
# v5.27.2. DO NOT EDIT: run the script, or wait for the "Update formula" workflow.
class Muster < Formula
  desc "One MCP endpoint for every MCP server your platform runs"
  homepage "https://github.com/giantswarm/muster"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/giantswarm/muster/releases/download/v5.27.2/muster-darwin-amd64"
      sha256 "0baa9ad659f68a4ac368f62673377bc5ab5546a7369937a6bacfe25aba7e46af"
    end
    on_arm do
      url "https://github.com/giantswarm/muster/releases/download/v5.27.2/muster-darwin-arm64"
      sha256 "1a3a0340995fd6afefdc07420185e2d0f5a0b2e9efc15e4966c9fdca42bf7ab6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/giantswarm/muster/releases/download/v5.27.2/muster-linux-amd64"
      sha256 "74d82731a6fbc02c1514985b14b631a961797d080d0c1f0d0aa951c5d5a438c2"
    end
    on_arm do
      url "https://github.com/giantswarm/muster/releases/download/v5.27.2/muster-linux-arm64"
      sha256 "f7e5e252103ab9c6bfbdd651fff9e15f45bdcc0246839d86b8900d4ddb760f7c"
    end
  end

  def install
    bin.install Dir["muster-*"].first => "muster"
    # A release asset carries no file mode, and Homebrew's cleaner sets it
    # only after install; the completions below need to run the binary.
    chmod 0755, bin/"muster"
    generate_completions_from_executable(bin/"muster", "completion")
  end

  test do
    assert_match "muster version", shell_output("#{bin}/muster version")
  end
end
