# typed: false
# frozen_string_literal: true

# Generated by scripts/update-formula.sh from the giantswarm/muster release
# v5.33.2. DO NOT EDIT: run the script, or wait for the "Update formula" workflow.
class Muster < Formula
  desc "One MCP endpoint for every MCP server your platform runs"
  homepage "https://github.com/giantswarm/muster"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/giantswarm/muster/releases/download/v5.33.2/muster-darwin-amd64"
      sha256 "21845270a6986be0f53bf9e08e2338a20fce626a32d20d763a9e527616fb3638"
    end
    on_arm do
      url "https://github.com/giantswarm/muster/releases/download/v5.33.2/muster-darwin-arm64"
      sha256 "bbcdd45ae1f731e4606bf08c03faaf14acabc74d4818fc19014d04aa32021862"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/giantswarm/muster/releases/download/v5.33.2/muster-linux-amd64"
      sha256 "4e6c3735e908c5803905de7a64b5cd3e718bf6f333c223d4b940742ff2cb2df4"
    end
    on_arm do
      url "https://github.com/giantswarm/muster/releases/download/v5.33.2/muster-linux-arm64"
      sha256 "ff591b41bfd930dd069a55a0ca64e6b59e9e12779457fb83c8d6dc2f0795cf96"
    end
  end

  def install
    bin.install Dir["muster-*"].first => "muster"
    # A release asset carries no file mode, and Homebrew's cleaner sets it
    # only after install; the completions below need to run the binary.
    chmod 0755, bin/"muster"
    generate_completions_from_executable(bin/"muster", "completion")
  end

  test do
    assert_match "muster version", shell_output("#{bin}/muster version")
  end
end
