#!/usr/bin/env bash
# Regenerates Formula/muster.rb from the latest giantswarm/muster GitHub
# release. Exits 0 without changes when the formula is already current.
set -euo pipefail

REPO="giantswarm/muster"
FORMULA="$(dirname "$0")/../Formula/muster.rb"

latest_tag=$(curl -sSf ${GITHUB_TOKEN:+-H "Authorization: Bearer $GITHUB_TOKEN"} \
  "https://api.github.com/repos/$REPO/releases/latest" | jq -r .tag_name)
version="${latest_tag#v}"

if [[ -z "$version" || "$version" == "null" ]]; then
  echo "Could not determine latest release tag" >&2
  exit 1
fi

current=$(sed -n 's/^  version "\(.*\)"/\1/p' "$FORMULA")
if [[ "$current" == "$version" ]]; then
  echo "Formula already at $version, nothing to do"
  exit 0
fi

echo "Updating formula: $current -> $version"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

declare -A sha
for asset in muster-darwin-amd64 muster-darwin-arm64 muster-linux-amd64 muster-linux-arm64; do
  url="https://github.com/$REPO/releases/download/$latest_tag/$asset"
  curl -sSfL -o "$tmpdir/$asset" "$url"
  sha[$asset]=$(sha256sum "$tmpdir/$asset" | cut -d' ' -f1)
done

cat > "$FORMULA" <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by .github/workflows/update-formula.yaml. DO NOT EDIT.
class Muster < Formula
  desc "Universal Control Plane for AI Agents - MCP server aggregator"
  homepage "https://github.com/giantswarm/muster"
  version "$version"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/giantswarm/muster/releases/download/$latest_tag/muster-darwin-amd64"
      sha256 "${sha[muster-darwin-amd64]}"
    end
    on_arm do
      url "https://github.com/giantswarm/muster/releases/download/$latest_tag/muster-darwin-arm64"
      sha256 "${sha[muster-darwin-arm64]}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/giantswarm/muster/releases/download/$latest_tag/muster-linux-amd64"
      sha256 "${sha[muster-linux-amd64]}"
    end
    on_arm do
      url "https://github.com/giantswarm/muster/releases/download/$latest_tag/muster-linux-arm64"
      sha256 "${sha[muster-linux-arm64]}"
    end
  end

  def install
    bin.install Dir["muster-*"].first => "muster"
  end

  test do
    system "#{bin}/muster", "version"
  end
end
EOF

echo "Formula updated to $version"
